[package]
name = "cnpj_alfanumerico"
version = "0.1.0"
edition = "2021"
authors = ["Edson Moretti"]
description = "Validação e cálculo de dígitos verificadores para CNPJ alfanumérico"

[dependencies]
regex = "1.10.2"
clap = { version = "4.4.6", features = ["derive"] }
